WIFI_SSID="yourWIFI"
WIFI_PASSWORD="YourPassword"
NTP_HOST="0.adafruit.pool.ntp.org"
TZ_OFFSET=-5
NTP_INTERVAL=60

# weather settings # imperial or metric
UNITS="imperial"

# weatherwx.com (tempest) Data Authorization
TEMPEST_ENABLE=0 # 0 = disabled, 1 = enabled
TEMPEST_API_TOKEN="yourDataAuthorizationToken"
TEMPEST_STATION=0 #YourStationNumber

# openweathermap.org Data Authorization
OWM_ENABLE=0 # 0 = disabled, 1 = enabled
OWM_API_TOKEN="Your Token"
OWM_ZIP="zip/post code"
OWM_COUNTRY="US" # Please use ISO 3166 country codes