name: Release CI

on:
  release:
    types: [published]
    
jobs:
  upload-mpy-zips:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the current repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Create .version file
      run:
        echo '{ "version":"${{ github.event.release.tag_name }}" }' > src/.version
        
    - name: Run MPY Action
      uses: adafruit/build-mpy@v1.0.4
      #uses: jake1164/build-mpy@fetch-submodules-fix
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}        
        mpy-directory: "src"
        mpy-manifest-file: "mpy-manifest.txt"
        mpy-manifest-type: "exclude"
        zip-directory: "src"
        zip-filename: "tempest-weather-${{ github.event.release.tag_name }}.zip"
